job-defaults: &job-defaults
  working_directory: &working_directory
    ~/aws-maven
  attach_workspace: &attach_workspace
      attach_workspace:
        at: *working_directory
  test_results_directory: &test_results_directory
    /tmp/test-results

machine-setup: &machine-setup
  machine:
    enabled: true

# Template to save Maven dependency cache to restore it in another jobs
save-maven-cache: &save-maven-cache
  save_cache:
    key: aws-maven-{{ checksum "pom.xml" }}
    paths:
      - ~/.m2

restore-maven-cache: &restore-maven-cache
  restore_cache:
    key: aws-maven-{{ checksum "pom.xml" }}

setup-gpg: &setup-gpg
  run:
    name: "Configuring gpg"
    command: |
      echo -e "$GPG_SECRET_KEY" | gpg --import --no-tty --batch --yes

version: 2
jobs:
  build:
    <<: *job-defaults
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - *setup-gpg
      - checkout
      - run: mvn clean dependency:go-offline package install -U -Dmaven.test.skip.exec -T 2.0C -B

      - <<: *save-maven-cache
      - persist_to_workspace:
          root: ~/aws-maven
          paths:
            - "*"

  build-jdk-11:
    <<: *job-defaults
    docker:
      - image: quay.io/verygoodsecurity/java11:production-0.0.42
        auth:
          username: $QUAY_DOCKER_LOGIN
          password: $QUAY_DOCKER_LOGIN_PASSWORD
    steps:
      - *setup-gpg
      - checkout
      - run: mvn clean dependency:go-offline package install -U -Dmaven.test.skip.exec -T 2.0C -B

  test:
    <<: *job-defaults
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - *setup-gpg
      - *attach_workspace
      - <<: *restore-maven-cache
      - run: mvn verify

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-jdk-11:
          context: artifact-publisher

      - build:
          context: artifact-publisher
          filters:
            tags:
              only: /.*/

      - test:
          context: artifact-publisher
          requires:
            - build
